version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.0.0
  slack: circleci/slack@3.4.2

jobs:
  slack_test:
    executor: slack/alpine
    steps:
      - checkout
      - run:
          command: |
            ls -la
            echo "export vm_name='$(grep "vm_name" vars/variable.yml)'" >> $BASH_ENV
            echo "export vm_rg_name='$(grep "vm_rg_name" vars/variable.yml)'" >> $BASH_ENV
            source $BASH_ENV
      - slack/notify:
          webhook: ${SLACK_WEBHOOK}
          color: "#00ff7f"
          message: >
            Azure VM Backup処理が正常終了しました。\n
            対象リソース\n
            -----------------------\n
            ${vm_name}\n
            ${vm_rg_name}\n
            -----------------------\n
workflows:
  version: 2.1
  install:
    jobs:
      - slack_test
